version: '2.1'
services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - webapp-network
  web:
    image: kcpserver
    depends_on:
      - database
    ports:
      - 3002:3002
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge